// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ88QVDT8vOHmRM-idzNzomGDJbpDSKlg',
    appId: '1:375494364461:web:2a7072579c1e2cccc6d7a4',
    messagingSenderId: '375494364461',
    projectId: 'mobile-gis-4213',
    authDomain: 'mobile-gis-4213.firebaseapp.com',
    storageBucket: 'mobile-gis-4213.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18SUbcBmjpEP5p3JRFE1NxWtKXAdREx0',
    appId: '1:375494364461:android:9845f28990e67e82c6d7a4',
    messagingSenderId: '375494364461',
    projectId: 'mobile-gis-4213',
    storageBucket: 'mobile-gis-4213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3-sCxUn7D--9Nzys508tzk5trjKSR7M',
    appId: '1:375494364461:ios:f4868f9aa7b49d8bc6d7a4',
    messagingSenderId: '375494364461',
    projectId: 'mobile-gis-4213',
    storageBucket: 'mobile-gis-4213.firebasestorage.app',
    iosBundleId: 'com.example.gisMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3-sCxUn7D--9Nzys508tzk5trjKSR7M',
    appId: '1:375494364461:ios:f4868f9aa7b49d8bc6d7a4',
    messagingSenderId: '375494364461',
    projectId: 'mobile-gis-4213',
    storageBucket: 'mobile-gis-4213.firebasestorage.app',
    iosBundleId: 'com.example.gisMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ88QVDT8vOHmRM-idzNzomGDJbpDSKlg',
    appId: '1:375494364461:web:b39f48d1d8b59b96c6d7a4',
    messagingSenderId: '375494364461',
    projectId: 'mobile-gis-4213',
    authDomain: 'mobile-gis-4213.firebaseapp.com',
    storageBucket: 'mobile-gis-4213.firebasestorage.app',
  );
}
